export enum PostsActionType {
    GET_POSTS_REQUEST = "GET_POSTS_REQUEST", 
    GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS",
    GET_POSTS_FAILURE = "GET_POSTS_FAILURE"

} ;


export enum PostActionType {
  GET_POST_REQUEST = "GET_POST_REQUEST",
  GET_POST_SUCCESS = "GET_POST_SUCCESS",
  GET_POST_FAILURE = "GET_POST_FAILURE"
}